### ISSUE TITLE
quantification and differential expression analysis for RNase R treated samples

### ISSUE THREAD

**Issue by cuijr1995** [Kevinzjy/CIRIquant#4]
Hi kevin,
I'm not very clear  the steps of  "Generate RNase R effect corrected BSJ information" . Should I run CIRIquant with RNase R treated samples 2 times and add --RNaseR option with "the output gtf of the first time" on the second time? Moreover, how cao I do the differential expression analysis for RNase R treated samples?  I'd appreciate it if you could give me some advice. Thanks!

**Comment by Kevinzjy** [comment]
In order to remove RNase R effect, you need to have two paired samples (1 untreated + 1 RNase R treated), and use following steps.

1. Run CIRIquant with RNase R treated sample
2. Specific the output RNase R treated GTF using --RNase R option when runnning CIRIquant with the untreated data. 

Then, CIRIquant will generate the corrected expression values of circRNAs detected in your RNase R treated sample.

For differential expression analysis, you can use `CIRI_DE` command using output gtf after RNase R correction:

```bash
CIRI_DE -n control_corrected.gtf -c case_corrected.gtf -o CIRI_DE_corrected.csv
```

**Comment by cuijr1995** [comment]
Thanks very much!
